name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clippy
        run: cargo clippy -- -Dwarnings
  release:
    name: Release
    needs: [test, lint]
#    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog@^6.0.3
            @semantic-release/git@^10.0.1
            @semantic-release/github@^8.0.7
            @semantic-release-cargo/semantic-release-cargo@^2.1.67
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}